//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xMenuToolsProcessor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xMenuToolsProcessor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error.
        /// </summary>
        internal static string AccessError {
            get {
                return ResourceManager.GetString("AccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -attributesmenu.
        /// </summary>
        internal static string AttributesMenuArgs {
            get {
                return ResourceManager.GetString("AttributesMenuArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Files to Windows Firewall.
        /// </summary>
        internal static string Blocking {
            get {
                return ResourceManager.GetString("Blocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocking Files .
        /// </summary>
        internal static string BlockingFilesTitle {
            get {
                return ResourceManager.GetString("BlockingFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonClose {
            get {
                object obj = ResourceManager.GetObject("buttonClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonContinue {
            get {
                object obj = ResourceManager.GetObject("buttonContinue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonPause {
            get {
                object obj = ResourceManager.GetObject("buttonPause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Locked File.
        /// </summary>
        internal static string CannotBeDeleted2PTitle {
            get {
                return ResourceManager.GetString("CannotBeDeleted2PTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  cannot be deleted in its current state.
        ///
        ///Would you like to delete .
        /// </summary>
        internal static string CannotBeDeletedP1 {
            get {
                return ResourceManager.GetString("CannotBeDeletedP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  at next reboot?.
        /// </summary>
        internal static string CannotBeDeletedP2 {
            get {
                return ResourceManager.GetString("CannotBeDeletedP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -catchhandler.
        /// </summary>
        internal static string CatchHandlerArgs {
            get {
                return ResourceManager.GetString("CatchHandlerArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counting Files.
        /// </summary>
        internal static string CountingFiles {
            get {
                return ResourceManager.GetString("CountingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s) added to Windows Defender Firewall successfully.
        ///
        ///Would you like to view the results?.
        /// </summary>
        internal static string DialogMessageBlockFiles {
            get {
                return ResourceManager.GetString("DialogMessageBlockFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files with extension exe and dll have been added to the Windows Defender Firewall.
        ///
        ///Would you like to view the results?.
        /// </summary>
        internal static string DialogMessageBlockFolder {
            get {
                return ResourceManager.GetString("DialogMessageBlockFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No .exe or .dll files were found in the given directory..
        /// </summary>
        internal static string DialogMessageFail {
            get {
                return ResourceManager.GetString("DialogMessageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Completed with Errors.
        /// </summary>
        internal static string DialogTitleFail {
            get {
                return ResourceManager.GetString("DialogTitleFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Completed Successfully.
        /// </summary>
        internal static string DialogTitleSuccess {
            get {
                return ResourceManager.GetString("DialogTitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while file count is enumerated....
        /// </summary>
        internal static string FileCount {
            get {
                return ResourceManager.GetString("FileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may take a while.
        ///
        ///You will be notified when the operation is complete..
        /// </summary>
        internal static string FilesBlockingWarning {
            get {
                return ResourceManager.GetString("FilesBlockingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advfirewall firewall add rule name=.
        /// </summary>
        internal static string FirewallAddRuleP1 {
            get {
                return ResourceManager.GetString("FirewallAddRuleP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  dir=out program=.
        /// </summary>
        internal static string FirewallAddRuleP2 {
            get {
                return ResourceManager.GetString("FirewallAddRuleP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  action=block.
        /// </summary>
        internal static string FirewallAddRuleP3 {
            get {
                return ResourceManager.GetString("FirewallAddRuleP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -firewall.
        /// </summary>
        internal static string FirewallArgs {
            get {
                return ResourceManager.GetString("FirewallArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -firewallfiles.
        /// </summary>
        internal static string FirewallFilesArgs {
            get {
                return ResourceManager.GetString("FirewallFilesArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -firewallfolder.
        /// </summary>
        internal static string FirewallFolderArgs {
            get {
                return ResourceManager.GetString("FirewallFolderArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (inbound).
        /// </summary>
        internal static string inbound {
            get {
                return ResourceManager.GetString("inbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -install.
        /// </summary>
        internal static string InstallArgs {
            get {
                return ResourceManager.GetString("InstallArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -i.
        /// </summary>
        internal static string InstallArgsShort {
            get {
                return ResourceManager.GetString("InstallArgsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation is complete!.
        /// </summary>
        internal static string InstallationComplete {
            get {
                return ResourceManager.GetString("InstallationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  into this directory?
        ///
        ///If you would like to install elsewhere, please press no..
        /// </summary>
        internal static string InstallNotice {
            get {
                return ResourceManager.GetString("InstallNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to install .
        /// </summary>
        internal static string InstallQuestion {
            get {
                return ResourceManager.GetString("InstallQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: .
        /// </summary>
        internal static string labelFileName {
            get {
                return ResourceManager.GetString("labelFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder: .
        /// </summary>
        internal static string labelFolderName {
            get {
                return ResourceManager.GetString("labelFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MAIN_ICON {
            get {
                object obj = ResourceManager.GetObject("MAIN_ICON", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MAIN_ICON_256 {
            get {
                object obj = ResourceManager.GetObject("MAIN_ICON_256", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -makelink.
        /// </summary>
        internal static string MakeLink {
            get {
                return ResourceManager.GetString("MakeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Files/Folders Selected.
        /// </summary>
        internal static string MultipleFiles {
            get {
                return ResourceManager.GetString("MultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed with errors..
        /// </summary>
        internal static string OperationError {
            get {
                return ResourceManager.GetString("OperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully!.
        /// </summary>
        internal static string OperationSuccess {
            get {
                return ResourceManager.GetString("OperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (outbound).
        /// </summary>
        internal static string outbound {
            get {
                return ResourceManager.GetString("outbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -ownership.
        /// </summary>
        internal static string OwnershipArgs {
            get {
                return ResourceManager.GetString("OwnershipArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while requested operation is completed....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while ownership is obtained....
        /// </summary>
        internal static string PleaseWaitOwner {
            get {
                return ResourceManager.GetString("PleaseWaitOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -refresh.
        /// </summary>
        internal static string RefreshArgs {
            get {
                return ResourceManager.GetString("RefreshArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\xMenuTools.
        /// </summary>
        internal static string RegUninstallKey32String {
            get {
                return ResourceManager.GetString("RegUninstallKey32String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\xMenuTools.
        /// </summary>
        internal static string RegUninstallKey64String {
            get {
                return ResourceManager.GetString("RegUninstallKey64String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to schedule .
        /// </summary>
        internal static string ScheduleErrorP1 {
            get {
                return ResourceManager.GetString("ScheduleErrorP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  for deletion
        ///
        ///You may need to take ownership first..
        /// </summary>
        internal static string ScheduleErrorP2 {
            get {
                return ResourceManager.GetString("ScheduleErrorP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select None.
        /// </summary>
        internal static string SelectNone {
            get {
                return ResourceManager.GetString("SelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Hidden (Unauthorized).
        /// </summary>
        internal static string SetHiddenUnauthorized {
            get {
                return ResourceManager.GetString("SetHiddenUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Read-only (Unauthorized).
        /// </summary>
        internal static string SetReadOnlyUnauthorized {
            get {
                return ResourceManager.GetString("SetReadOnlyUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as System (Unauthorized).
        /// </summary>
        internal static string SetSystemUnauthorized {
            get {
                return ResourceManager.GetString("SetSystemUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -settings.
        /// </summary>
        internal static string SettingArgs {
            get {
                return ResourceManager.GetString("SettingArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -s.
        /// </summary>
        internal static string SettingArgsShort {
            get {
                return ResourceManager.GetString("SettingArgsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taking Ownership.
        /// </summary>
        internal static string TakingOwnership {
            get {
                return ResourceManager.GetString("TakingOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Thread to finish before starting the next operation....
        /// </summary>
        internal static string ThreadWait {
            get {
                return ResourceManager.GetString("ThreadWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Trying the operation again....
        /// </summary>
        internal static string TryingAgain {
            get {
                return ResourceManager.GetString("TryingAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        internal static string UnauthorizedAccessException2PTitle {
            get {
                return ResourceManager.GetString("UnauthorizedAccessException2PTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may need to close .
        /// </summary>
        internal static string UnauthorizedAccessExceptionP1 {
            get {
                return ResourceManager.GetString("UnauthorizedAccessExceptionP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  first before you can make any changes.
        ///
        ///Otherwise you may not have permissions to change time attributes for .
        /// </summary>
        internal static string UnauthorizedAccessExceptionP2 {
            get {
                return ResourceManager.GetString("UnauthorizedAccessExceptionP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall.
        /// </summary>
        internal static string Uninstall32Bit {
            get {
                return ResourceManager.GetString("Uninstall32Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall.
        /// </summary>
        internal static string Uninstall64Bit {
            get {
                return ResourceManager.GetString("Uninstall64Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -uninstall.
        /// </summary>
        internal static string UninstallArgs {
            get {
                return ResourceManager.GetString("UninstallArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -u.
        /// </summary>
        internal static string UninstallArgsShort {
            get {
                return ResourceManager.GetString("UninstallArgsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall is complete.
        ///
        ///Would you like to restart Explorer now?.
        /// </summary>
        internal static string UninstallComplete {
            get {
                return ResourceManager.GetString("UninstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string UninstallNotice {
            get {
                return ResourceManager.GetString("UninstallNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to uninstall .
        /// </summary>
        internal static string UninstallQuestion {
            get {
                return ResourceManager.GetString("UninstallQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xCONFLiCTiONx  |  xMenuTools .
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You may not have write permissions..
        /// </summary>
        internal static string WritePermissions {
            get {
                return ResourceManager.GetString("WritePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xMenuTools.
        /// </summary>
        internal static string xMenuTools {
            get {
                return ResourceManager.GetString("xMenuTools", resourceCulture);
            }
        }
    }
}
