//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xMenuTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xMenuTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon AttributesHide {
            get {
                object obj = ResourceManager.GetObject("AttributesHide", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes Menu.
        /// </summary>
        internal static string AttributesMenu {
            get {
                return ResourceManager.GetString("AttributesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon AttributesShow {
            get {
                object obj = ResourceManager.GetObject("AttributesShow", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string AttributesText {
            get {
                return ResourceManager.GetString("AttributesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block all with Firewall.
        /// </summary>
        internal static string BlockAllText {
            get {
                return ResourceManager.GetString("BlockAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block with Firewall.
        /// </summary>
        internal static string BlockText {
            get {
                return ResourceManager.GetString("BlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon cmd {
            get {
                object obj = ResourceManager.GetObject("cmd", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Lines.
        /// </summary>
        internal static string CommandLines {
            get {
                return ResourceManager.GetString("CommandLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Prompt.
        /// </summary>
        internal static string CommandPrompt {
            get {
                return ResourceManager.GetString("CommandPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Prompt (Admin).
        /// </summary>
        internal static string CommandPromptElevated {
            get {
                return ResourceManager.GetString("CommandPromptElevated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon CopyName {
            get {
                object obj = ResourceManager.GetObject("CopyName", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Name.
        /// </summary>
        internal static string CopyNameText {
            get {
                return ResourceManager.GetString("CopyNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon CopyPath {
            get {
                object obj = ResourceManager.GetObject("CopyPath", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Path.
        /// </summary>
        internal static string CopyPathText {
            get {
                return ResourceManager.GetString("CopyPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Symbolic Link (Junction).
        /// </summary>
        internal static string CreateSymbolicLink {
            get {
                return ResourceManager.GetString("CreateSymbolicLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon FileAttributes {
            get {
                object obj = ResourceManager.GetObject("FileAttributes", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon FindWallpaper {
            get {
                object obj = ResourceManager.GetObject("FindWallpaper", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Wallpaper.
        /// </summary>
        internal static string FindWallpaperText {
            get {
                return ResourceManager.GetString("FindWallpaperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Firewall {
            get {
                object obj = ResourceManager.GetObject("Firewall", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon FolderAttributes {
            get {
                object obj = ResourceManager.GetObject("FolderAttributes", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon FolderIcon {
            get {
                object obj = ResourceManager.GetObject("FolderIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GitCmd {
            get {
                object obj = ResourceManager.GetObject("GitCmd", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Hidden Attribute.
        /// </summary>
        internal static string HiddenAttributes {
            get {
                return ResourceManager.GetString("HiddenAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Hidden.
        /// </summary>
        internal static string HideHidden {
            get {
                return ResourceManager.GetString("HideHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide System.
        /// </summary>
        internal static string HideSystem {
            get {
                return ResourceManager.GetString("HideSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MAIN_ICON {
            get {
                object obj = ResourceManager.GetObject("MAIN_ICON", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MAIN_ICON_256 {
            get {
                object obj = ResourceManager.GetObject("MAIN_ICON_256", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon notepad {
            get {
                object obj = ResourceManager.GetObject("notepad", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git-cmd (Admin).
        /// </summary>
        internal static string OpenGitAsAdmin {
            get {
                return ResourceManager.GetString("OpenGitAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git-cmd.
        /// </summary>
        internal static string OpenGitAsUser {
            get {
                return ResourceManager.GetString("OpenGitAsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with Notepad.
        /// </summary>
        internal static string OpenNotepad {
            get {
                return ResourceManager.GetString("OpenNotepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powershell (Admin).
        /// </summary>
        internal static string OpenPSAsAdmin {
            get {
                return ResourceManager.GetString("OpenPSAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powershell.
        /// </summary>
        internal static string OpenPSAsUser {
            get {
                return ResourceManager.GetString("OpenPSAsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal.
        /// </summary>
        internal static string OpenTerminal {
            get {
                return ResourceManager.GetString("OpenTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal (Admin).
        /// </summary>
        internal static string OpenTerminalElevated {
            get {
                return ResourceManager.GetString("OpenTerminalElevated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PS {
            get {
                object obj = ResourceManager.GetObject("PS", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Read-only Attribute.
        /// </summary>
        internal static string ReadOnlyAttributes {
            get {
                return ResourceManager.GetString("ReadOnlyAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Attributes.
        /// </summary>
        internal static string SetAttributes {
            get {
                return ResourceManager.GetString("SetAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hidden.
        /// </summary>
        internal static string ShowHidden {
            get {
                return ResourceManager.GetString("ShowHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show System.
        /// </summary>
        internal static string ShowSystem {
            get {
                return ResourceManager.GetString("ShowSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon SymLink {
            get {
                object obj = ResourceManager.GetObject("SymLink", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set System Attribute.
        /// </summary>
        internal static string SystemAttributes {
            get {
                return ResourceManager.GetString("SystemAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon SystemIcon {
            get {
                object obj = ResourceManager.GetObject("SystemIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon TakeOwnership {
            get {
                object obj = ResourceManager.GetObject("TakeOwnership", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Ownership.
        /// </summary>
        internal static string TakeOwnershipText {
            get {
                return ResourceManager.GetString("TakeOwnershipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon terminal {
            get {
                object obj = ResourceManager.GetObject("terminal", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xMenuTools.
        /// </summary>
        internal static string xMenuToolsName {
            get {
                return ResourceManager.GetString("xMenuToolsName", resourceCulture);
            }
        }
    }
}
